# Generated by Django 5.0.5 on 2024-05-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_foto_quarto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='foto_quarto',
        ),
        migrations.AddField(
            model_name='quarto',
            name='foto_quarto',
            field=models.ImageField(default=0, upload_to='Foto_Quarto/'),
            preserve_default=False,
        ),
    ]
