# Generated by Django 5.0.5 on 2024-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_foto_quarto_quarto_foto_quarto'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('idade', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('quarto', models.CharField(choices=[('SOLTEIRO', 'solteiro'), ('CASAL', 'casal'), ('CONFORTO', 'conforto'), ('LUXO', 'luxo')], max_length=15)),
            ],
        ),
    ]
