# Generated by Django 5.0.5 on 2024-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='valor',
            field=models.FloatField(max_length=4),
        ),
    ]
