# Generated by Django 5.0.5 on 2024-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_quarto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='foto',
            field=models.ImageField(default=0, upload_to='hotel_foto/'),
            preserve_default=False,
        ),
    ]
